/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://igybkfjnivdkxac5qxmuofejse.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-edzsja4uongpvhxksmklterzra",
    "aws_cognito_identity_pool_id": "us-west-2:3a358646-b76f-422f-ac62-a07ef9543f0c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_lIjSIP5uK",
    "aws_user_pools_web_client_id": "47ph465774js1i636usklcncg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bckandy15523-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
